name: Test
on:
  pull_request:
    paths-ignore:  # ignore docs as they are built with Netlify.
      - '**/*.md'
      - 'site/**'
      - 'netlify.toml'
  push:
    paths-ignore:  # ignore docs as they are built with Netlify.
      - '**/*.md'
      - 'site/**'
      - 'netlify.toml'

env:  # Update this prior to requiring a higher minor version in go.mod
  GO_VERSION: "1.22"

defaults:
  run:  # use bash for all operating systems unless overridden
    shell: bash

concurrency:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:

  test:
    name: ${{ matrix.platform.arch }}, ${{ matrix.platform.os }}, Go-${{ matrix.go-version }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are arch/OS specific
      matrix:  # Use versions consistent with wazero's Go support policy.
        platform:
        - os: ubuntu-22.04
          arch: amd64
        - os: macos-12
          arch: amd64
        - os: windows-2022
          arch: amd64
        - os: macos-14
          arch: arm64
        go-version:
          - "1.22"  # Current Go version

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      # Ensure the pagefile is large enough to execute tests like TestStore_hammer_close on Windows.
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        if: runner.os == 'Windows'
        with:
          minimum-size: 8GB
          maximum-size: 16GB
          disk-root: "D:"

      - name: "Install Wazero"
        run: |
          git clone https://github.com/tetratelabs/wazero
          cd wazero
          go install ./cmd/wazero
          cd ..

      - name: "Run Wazero (old compiler)"
        run: |
          cd 2022-12/wasm
          for I in *
          do
                  echo -n $I:\  && wazero run $I
          done

      - name: "Run Wazero (optimizing compiler)"
        run: |
          cd 2022-12/wasm
          for I in *
          do
                  echo -n $I:\  && wazero run -optimizing-compiler $I
          done


